# Generated by Django 5.1.4 on 2024-12-24 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('section', models.CharField(blank=True, max_length=1, null=True)),
                ('age', models.IntegerField(null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('category', models.CharField(blank=True, max_length=2, null=True)),
                ('medium', models.CharField(blank=True, max_length=50, null=True)),
                ('school', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
