# Generated by Django 5.1.4 on 2024-12-25 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_section_delete_students'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField(null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('category', models.CharField(blank=True, max_length=2, null=True)),
                ('medium', models.CharField(blank=True, max_length=50, null=True)),
                ('school', models.CharField(blank=True, max_length=50, null=True)),
                ('section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='students.section')),
            ],
        ),
    ]
