# Generated by Django 5.1.4 on 2024-12-25 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_students'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='students',
            options={'ordering': ['name']},
        ),
    ]
