# Generated by Django 5.1.4 on 2025-01-14 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_students_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='batch',
            field=models.IntegerField(null=True),
        ),
    ]
