# Generated by Django 5.1.4 on 2025-01-25 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_alter_students_options_remove_students_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='students',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='students',
            name='_name',
        ),
        migrations.AddField(
            model_name='students',
            name='name',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
