# Generated by Django 5.1.4 on 2025-02-12 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='students.batch'),
        ),
    ]
