# Generated by Django 5.1.4 on 2025-02-12 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_alter_students_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
