# Generated by Django 5.1.4 on 2025-02-12 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_alter_section_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='batch_no',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.batch'),
        ),
    ]
