# Generated by Django 5.1.4 on 2025-02-12 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_alter_batch_batch_no_alter_students_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='batch',
            field=models.IntegerField(null=True),
        ),
    ]
