# Generated by Django 5.1.4 on 2025-02-12 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_alter_students_batch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='batch',
        ),
    ]
