# Generated by Django 5.1.4 on 2025-02-12 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0014_students_batch_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='batch_id',
            new_name='batch',
        ),
    ]
