# Generated by Django 5.1.4 on 2025-02-12 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0015_rename_batch_id_students_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='category',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C+', 'C+'), ('D', 'D'), ('E', 'E')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='medium',
            field=models.CharField(blank=True, choices=[('Tamil', 'Tamil'), ('English', 'English'), ('Other', 'Other')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='school',
            field=models.CharField(blank=True, choices=[('Private', 'Private'), ('Govt', 'Government'), ('Govt-Aided', 'Government-Aided')], max_length=15, null=True),
        ),
    ]
