# Generated by Django 5.1.4 on 2024-12-29 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='short_form',
            field=models.CharField(max_length=5, null=True, unique=True),
        ),
    ]
