# Generated by Django 5.1.4 on 2025-01-11 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_status_short_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='short_form',
            field=models.CharField(max_length=8, null=True, unique=True),
        ),
    ]
