# Generated by Django 5.1.4 on 2025-03-20 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='image',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
