# Generated by Django 5.1.4 on 2025-03-26 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_alter_member_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='image',
            new_name='image_link',
        ),
    ]
