# Generated by Django 5.1.4 on 2024-12-24 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mark',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='mark',
            name='mark',
        ),
        migrations.RemoveField(
            model_name='mark',
            name='month',
        ),
        migrations.RemoveField(
            model_name='mark',
            name='remark',
        ),
        migrations.RemoveField(
            model_name='mark',
            name='student',
        ),
        migrations.RemoveField(
            model_name='mark',
            name='subject',
        ),
    ]
