# Generated by Django 5.1.4 on 2024-12-25 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testdetail',
            name='isArchived',
            field=models.BooleanField(default=False),
        ),
    ]
