# Generated by Django 5.1.4 on 2024-12-24 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0002_remove_mark_created_at_remove_mark_mark_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mark',
        ),
    ]
