# Generated by Django 5.1.4 on 2024-12-25 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0002_testdetail_isarchived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='average_mark',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='mark',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
