# Generated by Django 5.1.4 on 2024-12-24 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0003_delete_mark'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('remark', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marks.month')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.students')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marks.subject')),
            ],
        ),
    ]
