# Generated by Django 5.1.4 on 2024-12-27 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0003_alter_marks_average_mark_alter_marks_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testdetail',
            name='created_at',
            field=models.DateField(),
        ),
    ]
