# Generated by Django 5.1.4 on 2024-12-27 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0004_alter_testdetail_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testdetail',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
