# Generated by Django 5.1.4 on 2024-12-29 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0005_alter_testdetail_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='testdetail',
            name='about_test',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
