# Generated by Django 5.1.4 on 2025-01-06 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0006_testdetail_about_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marks',
            name='average_mark',
        ),
    ]
