# Generated by Django 5.1.4 on 2025-01-14 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0008_testlevels'),
    ]

    operations = [
        migrations.AddField(
            model_name='testdetail',
            name='isLevelTest',
            field=models.BooleanField(default=False),
        ),
    ]
