# Generated by Django 5.1.4 on 2025-01-14 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0009_testdetail_isleveltest'),
    ]

    operations = [
        migrations.AddField(
            model_name='testdetail',
            name='batch',
            field=models.IntegerField(null=True),
        ),
    ]
