# Generated by Django 5.1.4 on 2025-01-18 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0010_testdetail_batch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testdetail',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='testdetail',
            name='isLevelTest',
        ),
        migrations.AddField(
            model_name='testlevels',
            name='remark',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
