# Generated by Django 5.1.4 on 2025-01-19 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0011_remove_testdetail_batch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testdetail',
            name='isLevelTest',
            field=models.BooleanField(default=False),
        ),
    ]
