# Generated by Django 5.1.4 on 2025-01-23 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0012_testdetail_isleveltest'),
    ]

    operations = [
        migrations.AddField(
            model_name='testdetail',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
