# Generated by Django 5.1.4 on 2025-01-25 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0014_remove_testdetail_section'),
        ('students', '0006_alter_students_options_remove_students_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marks',
            name='mark',
        ),
        migrations.RemoveField(
            model_name='marks',
            name='remark',
        ),
        migrations.RemoveField(
            model_name='testdetail',
            name='isArchived',
        ),
        migrations.AddField(
            model_name='marks',
            name='_mark',
            field=models.TextField(db_column='mark', default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marks',
            name='_remark',
            field=models.TextField(blank=True, db_column='remark', null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='students.students'),
        ),
        migrations.AlterField(
            model_name='marks',
            name='test_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='marks.testdetail'),
        ),
    ]
