# Generated by Django 5.1.4 on 2025-01-25 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0015_remove_marks_mark_remove_marks_remark_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='_mark',
            field=models.TextField(blank=True, db_column='mark', null=True),
        ),
    ]
