# Generated by Django 5.1.4 on 2025-03-19 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0018_alter_testdetail_batch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marks',
            name='_mark',
        ),
        migrations.RemoveField(
            model_name='marks',
            name='_remark',
        ),
        migrations.AddField(
            model_name='marks',
            name='mark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marks',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
