# Generated by Django 5.1.4 on 2025-03-29 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0020_alter_marks_student_alter_marks_test_detail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='mark',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
